name: Fetch Job Listings

on:
  schedule:
    # Set the schedule when you want to run the script (e.g., every day at 00:00 UTC)
    - cron: '0 0 * * *'

jobs:
  fetch_job_listings:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pandas

      - name: Run script
        run: python job_listings_area.py
